### ISSUE TITLE
Native Method Hooking

### ISSUE THREAD

**Issue by KieronQuinn** [Aliucord/hook#1]
I'm using this library in one of my projects, but have noticed something a little odd.

In `XposedBridge.checkMethod()` you check if the method is native, and reject if it is:

```
if (Modifier.isAbstract(modifiers))
     throw new IllegalArgumentException("method must not be abstract");
```

Only, you can actually hook native methods using LSPlant. The behaviour is not perfect, granted - modifying arguments doesn't seem to work properly (I think the native code might be called before `beforeHookedMethod`), but you _can_ hook it, which is useful if you want to intercept the result of a native method, whose names are usually not obfuscated.

Please consider removing the check, perhaps including a warning somewhere of the behaviour instead, thanks.

**Comment by Vendicated** [comment]
Yeah, I realised this as well recently. I don't remember why I added this check, perhaps adapted from original Xposed? 

I will remove it 👌

**Comment by Vendicated** [comment]
Fixed in https://github.com/Aliucord/hook/commit/e95edcf359be662a628caa6ea9e070608057ddbf.
It works well, even replacing arguments in beforeHookedMethod worked for me. If replacing arguments still doesn't work for you, please open another issue with example code and I can investigate

Thanks for the report!
